In [1]:
import paho.mqtt.client as mqtt
import json
import psycopg2
from psycopg2 import pool
from psycopg2.extras import execute_values
from datetime import datetime

# --- SETTINGS ---
MQTT_BROKER = "192.168.1.100"
MQTT_PORT = 1883
MQTT_TOPIC = "home/sniffers"

# Database URL
DB_URL = "postgresql://aragorn:aragorndb@aragorndb.home:5432/wsts"

# --- DATABASE SETUP ---
try:
    db_pool = psycopg2.pool.SimpleConnectionPool(1, 10, DB_URL)
    print("✅ Connected to PostgreSQL Pool")
except Exception as e:
    print(f"❌ Database Connection Error: {e}")
    exit(1)

def init_db():
    conn = db_pool.getconn()
    cur = conn.cursor()
    # Added vcc column (storing as INTEGER to keep millivolts)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS rssi_signals.sniffer_data (
            id SERIAL PRIMARY KEY,
            timestamp TIMESTAMP,
            sensor_id VARCHAR(50),
            vcc INTEGER,
            mac_address VARCHAR(20),
            rssi INTEGER
        )
    """)
    conn.commit()
    cur.close()
    db_pool.putconn(conn)
    print("✅ Table 'rssi_signals.sniffer_data'.")

# --- MQTT CALLBACKS ---
def on_connect(client, userdata, flags, rc, properties=None):
    if rc == 0:
        print(f"✅ Connected to Mosquitto")
        client.subscribe(MQTT_TOPIC)
    else:
        print(f"❌ MQTT Connection failed: {rc}")

def on_message(client, userdata, msg):
    conn = None
    try:
        payload = json.loads(msg.payload.decode())
        sensor_id = payload.get("sensor", "Unknown")
        vcc = payload.get("vcc", 0) # Get the battery voltage
        timestamp = datetime.now()
        devices = payload.get("data", [])

        if not devices:
            return

        # Prepare data: adding 'vcc' to every row for this sensor report
        values = [(timestamp, sensor_id, vcc, d["m"], d["r"]) for d in devices]

        # Get connection from pool and insert
        conn = db_pool.getconn()
        cur = conn.cursor()
        query = """
            INSERT INTO rssi_signals.sniffer_data (timestamp, sensor_id, vcc, mac_address, rssi) 
            VALUES %s
        """
        execute_values(cur, query, values)
        
        conn.commit()
        cur.close()
        db_pool.putconn(conn)
        
        print(f"[{timestamp.strftime('%H:%M:%S')}] {sensor_id} ({vcc}mV): Saved {len(devices)} devices.")

    except Exception as e:
        print(f"❌ Error: {e}")
        if conn:
            db_pool.putconn(conn)

# --- EXECUTION ---
init_db()

client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
client.on_connect = on_connect
client.on_message = on_message

print(f"Connecting to MQTT Broker at {MQTT_BROKER}...")
try:
    client.connect(MQTT_BROKER, MQTT_PORT)
    client.loop_forever()
except KeyboardInterrupt:
    print("\nStopping script...")
except Exception as e:
    print(f"❌ Critical Error: {e}")

✅ Connected to PostgreSQL Pool
✅ Table 'rssi_signals.sniffer_data'.
Connecting to MQTT Broker at 192.168.1.100...
✅ Connected to Mosquitto
[21:00:53] 8C:AA:B5:48:4F:13 (3462mV): Saved 29 devices.
[21:01:28] 8C:AA:B5:48:4F:13 (3462mV): Saved 29 devices.
[21:02:03] 8C:AA:B5:48:4F:13 (3463mV): Saved 27 devices.
[21:02:37] 8C:AA:B5:48:4F:13 (3462mV): Saved 24 devices.
[21:03:11] 8C:AA:B5:48:4F:13 (3462mV): Saved 28 devices.
[21:03:46] 8C:AA:B5:48:4F:13 (3462mV): Saved 25 devices.
[21:04:21] 8C:AA:B5:48:4F:13 (3462mV): Saved 29 devices.

Stopping script...

In [4]:
import paho.mqtt.client as mqtt
import json
import pandas as pd
import time
from datetime import datetime
import threading

# --- CONFIGURATION ---
MQTT_BROKER = "192.168.1.100"  # Your Docker IP
MQTT_TOPIC = "home/sniffers"
messages_list = []

# --- CALLBACKS ---
def on_message(client, userdata, msg):
    try:
        payload = json.loads(msg.payload.decode())
        sensor_id = payload.get("sensor", "Unknown")
        timestamp = datetime.now()
        
        # Flatten the nested data for a clean table
        for device in payload.get("data", []):
            messages_list.append({
                "timestamp": timestamp,
                "sensor": sensor_id,
                "mac": device["m"],
                "rssi": device["r"]
            })
        print(f"[{timestamp.strftime('%H:%M:%S')}] Logged {len(payload.get('data', []))} devices from {sensor_id}")
    except Exception as e:
        print(f"Error parsing message: {e}")

# --- MQTT SETUP ---
client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
client.on_message = on_message

def start_mqtt():
    client.connect(MQTT_BROKER, 1883)
    client.subscribe(MQTT_TOPIC)
    client.loop_forever()

# Start the MQTT client in a separate thread so it doesn't block the notebook
mqtt_thread = threading.Thread(target=start_mqtt, daemon=True)
mqtt_thread.start()

print(f"Listening for data on {MQTT_TOPIC}... Run the next cell whenever you want to see the data.")

Listening for data on home/sniffers... Run the next cell whenever you want to see the data.

In [9]:
messages_list

[{'timestamp': datetime.datetime(2026, 3, 1, 13, 27, 41, 463329),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '54:1f:8d:da:d6:9d',
  'rssi': -76},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 27, 41, 463329),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '30:16:9d:88:47:90',
  'rssi': -60},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 27, 41, 463329),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '14:33:75:ab:0f:71',
  'rssi': -76},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 27, 41, 463329),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'a4:91:b1:bf:11:77',
  'rssi': -63},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 27, 41, 463329),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '6c:99:61:24:54:b4',
  'rssi': -83},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 27, 41, 465491),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '54:1f:8d:da:d6:9d',
  'rssi': -76},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 27, 41, 465491),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '30:16:9d:88:47:90',
  'rssi': -60},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 27, 41, 465491),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '14:33:75:ab:0f:71',
  'rssi': -76},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 27, 41, 465491),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'a4:91:b1:bf:11:77',
  'rssi': -63},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 27, 41, 465491),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '6c:99:61:24:54:b4',
  'rssi': -83},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313831),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '54:1f:8d:da:d6:9d',
  'rssi': -73},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313831),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '30:16:9d:88:47:90',
  'rssi': -69},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313831),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '14:33:75:ab:0f:71',
  'rssi': -77},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313831),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'a4:91:b1:bf:11:77',
  'rssi': -64},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313831),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'e6:63:da:b7:68:41',
  'rssi': -80},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313831),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '6c:99:61:24:54:b4',
  'rssi': -82},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313831),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'e0:63:da:b7:68:41',
  'rssi': -81},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313952),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '54:1f:8d:da:d6:9d',
  'rssi': -73},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313952),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '30:16:9d:88:47:90',
  'rssi': -69},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313952),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '14:33:75:ab:0f:71',
  'rssi': -77},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313952),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'a4:91:b1:bf:11:77',
  'rssi': -64},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313952),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'e6:63:da:b7:68:41',
  'rssi': -80},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313952),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '6c:99:61:24:54:b4',
  'rssi': -82},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 16, 313952),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'e0:63:da:b7:68:41',
  'rssi': -81},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153392),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '14:33:75:ab:0f:71',
  'rssi': -78},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153392),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '30:16:9d:88:47:90',
  'rssi': -60},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153392),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'a4:91:b1:bf:11:77',
  'rssi': -63},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153392),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '54:1f:8d:da:d6:9d',
  'rssi': -74},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153392),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '6c:99:61:24:54:b4',
  'rssi': -81},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153392),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'e6:63:da:b7:68:41',
  'rssi': -82},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153558),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '14:33:75:ab:0f:71',
  'rssi': -78},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153558),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '30:16:9d:88:47:90',
  'rssi': -60},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153558),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'a4:91:b1:bf:11:77',
  'rssi': -63},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153558),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '54:1f:8d:da:d6:9d',
  'rssi': -74},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153558),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': '6c:99:61:24:54:b4',
  'rssi': -81},
 {'timestamp': datetime.datetime(2026, 3, 1, 13, 28, 51, 153558),
  'sensor': '8C:AA:B5:48:4F:13',
  'mac': 'e6:63:da:b7:68:41',
  'rssi': -82}]

[13:29:28] Logged 6 devices from 8C:AA:B5:48:4F:13[13:29:28] Logged 6 devices from 8C:AA:B5:48:4F:13

[13:30:03] Logged 6 devices from 8C:AA:B5:48:4F:13[13:30:03] Logged 6 devices from 8C:AA:B5:48:4F:13

[13:30:38] Logged 4 devices from 8C:AA:B5:48:4F:13[13:30:38] Logged 4 devices from 8C:AA:B5:48:4F:13

[13:31:15] Logged 14 devices from 8C:AA:B5:48:4F:13
[13:31:15] Logged 14 devices from 8C:AA:B5:48:4F:13
[13:31:50] Logged 11 devices from 8C:AA:B5:48:4F:13[13:31:50] Logged 11 devices from 8C:AA:B5:48:4F:13

[13:32:24] Logged 11 devices from 8C:AA:B5:48:4F:13[13:32:24] Logged 11 devices from 8C:AA:B5:48:4F:13

[13:32:59] Logged 14 devices from 8C:AA:B5:48:4F:13[13:32:59] Logged 14 devices from 8C:AA:B5:48:4F:13

[13:33:34] Logged 13 devices from 8C:AA:B5:48:4F:13[13:33:34] Logged 13 devices from 8C:AA:B5:48:4F:13

[13:34:09] Logged 18 devices from 8C:AA:B5:48:4F:13[13:34:09] Logged 18 devices from 8C:AA:B5:48:4F:13

[13:34:44] Logged 15 devices from 8C:AA:B5:48:4F:13[13:34:44] Logged 15 devices from 8C:AA:B5:48:4F:13

[13:35:18] Logged 12 devices from 8C:AA:B5:48:4F:13[13:35:18] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:35:53] Logged 14 devices from 8C:AA:B5:48:4F:13[13:35:53] Logged 14 devices from 8C:AA:B5:48:4F:13

[13:36:28] Logged 12 devices from 8C:AA:B5:48:4F:13[13:36:28] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:37:02] Logged 13 devices from 8C:AA:B5:48:4F:13[13:37:02] Logged 13 devices from 8C:AA:B5:48:4F:13

[13:37:36] Logged 15 devices from 8C:AA:B5:48:4F:13[13:37:36] Logged 15 devices from 8C:AA:B5:48:4F:13

[13:38:11] Logged 16 devices from 8C:AA:B5:48:4F:13[13:38:11] Logged 16 devices from 8C:AA:B5:48:4F:13

[13:38:46] Logged 15 devices from 8C:AA:B5:48:4F:13[13:38:46] Logged 15 devices from 8C:AA:B5:48:4F:13

[13:39:21] Logged 15 devices from 8C:AA:B5:48:4F:13[13:39:21] Logged 15 devices from 8C:AA:B5:48:4F:13

[13:39:56] Logged 12 devices from 8C:AA:B5:48:4F:13[13:39:56] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:40:31] Logged 15 devices from 8C:AA:B5:48:4F:13[13:40:31] Logged 15 devices from 8C:AA:B5:48:4F:13

[13:41:05] Logged 14 devices from 8C:AA:B5:48:4F:13
[13:41:05] Logged 14 devices from 8C:AA:B5:48:4F:13
[13:41:40] Logged 13 devices from 8C:AA:B5:48:4F:13
[13:41:40] Logged 13 devices from 8C:AA:B5:48:4F:13
[13:42:15] Logged 12 devices from 8C:AA:B5:48:4F:13[13:42:15] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:42:49] Logged 14 devices from 8C:AA:B5:48:4F:13[13:42:49] Logged 14 devices from 8C:AA:B5:48:4F:13

[13:43:24] Logged 13 devices from 8C:AA:B5:48:4F:13[13:43:24] Logged 13 devices from 8C:AA:B5:48:4F:13

[13:43:59] Logged 15 devices from 8C:AA:B5:48:4F:13[13:43:59] Logged 15 devices from 8C:AA:B5:48:4F:13

[13:44:34] Logged 15 devices from 8C:AA:B5:48:4F:13[13:44:34] Logged 15 devices from 8C:AA:B5:48:4F:13

[13:45:09] Logged 15 devices from 8C:AA:B5:48:4F:13[13:45:09] Logged 15 devices from 8C:AA:B5:48:4F:13

[13:45:43] Logged 12 devices from 8C:AA:B5:48:4F:13[13:45:43] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:46:18] Logged 13 devices from 8C:AA:B5:48:4F:13[13:46:18] Logged 13 devices from 8C:AA:B5:48:4F:13

[13:46:52] Logged 12 devices from 8C:AA:B5:48:4F:13[13:46:52] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:47:27] Logged 12 devices from 8C:AA:B5:48:4F:13[13:47:27] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:48:02] Logged 12 devices from 8C:AA:B5:48:4F:13[13:48:02] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:48:36] Logged 13 devices from 8C:AA:B5:48:4F:13
[13:48:36] Logged 13 devices from 8C:AA:B5:48:4F:13
[13:49:11] Logged 11 devices from 8C:AA:B5:48:4F:13[13:49:11] Logged 11 devices from 8C:AA:B5:48:4F:13

[13:49:45] Logged 12 devices from 8C:AA:B5:48:4F:13[13:49:45] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:50:20] Logged 12 devices from 8C:AA:B5:48:4F:13[13:50:20] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:50:55] Logged 12 devices from 8C:AA:B5:48:4F:13[13:50:55] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:51:29] Logged 10 devices from 8C:AA:B5:48:4F:13[13:51:29] Logged 10 devices from 8C:AA:B5:48:4F:13

[13:52:04] Logged 14 devices from 8C:AA:B5:48:4F:13
[13:52:04] Logged 14 devices from 8C:AA:B5:48:4F:13
[13:52:39] Logged 11 devices from 8C:AA:B5:48:4F:13[13:52:39] Logged 11 devices from 8C:AA:B5:48:4F:13

[13:53:13] Logged 10 devices from 8C:AA:B5:48:4F:13[13:53:13] Logged 10 devices from 8C:AA:B5:48:4F:13

[13:53:51] Logged 14 devices from 8C:AA:B5:48:4F:13[13:53:51] Logged 14 devices from 8C:AA:B5:48:4F:13

[13:54:26] Logged 14 devices from 8C:AA:B5:48:4F:13[13:54:26] Logged 14 devices from 8C:AA:B5:48:4F:13

[13:55:01] Logged 12 devices from 8C:AA:B5:48:4F:13[13:55:01] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:55:35] Logged 11 devices from 8C:AA:B5:48:4F:13[13:55:35] Logged 11 devices from 8C:AA:B5:48:4F:13

[13:56:10] Logged 11 devices from 8C:AA:B5:48:4F:13[13:56:10] Logged 11 devices from 8C:AA:B5:48:4F:13

In [13]:
# Convert the collected list into a Pandas DataFrame
df = pd.DataFrame(messages_list)

if not df.empty:
    # Save to CSV for backup
    df.to_csv("sniff_data.csv", index=False)
    
    print(f"Total rows collected: {len(df)}")
    # Show the last 10 sightings
    display(df.tail(10))
    
    # Quick analysis: Show which sensor sees the most devices
    print("\nDevices per Sensor:")
    print(df.groupby("sensor")["mac"].count())
else:
    print("No data collected yet. Check if ESP01 is publishing!")

Total rows collected: 1240

                      timestamp             sensor                mac  rssi
1230 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  e0:63:da:b7:68:41   -83
1231 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  e6:63:da:b7:68:41   -88
1232 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  e6:63:da:b7:68:21   -85
1233 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  30:16:9d:88:47:90   -62
1234 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  6c:99:61:24:54:b4   -87
1235 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  e0:63:da:b7:68:21   -85
1236 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  14:33:75:ab:0f:71   -77
1237 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  80:16:05:e4:87:08   -86
1238 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  ae:8b:a9:9a:3b:6a   -88
1239 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  d0:b6:6f:57:6b:75   -86

Devices per Sensor:
sensor
8C:AA:B5:48:4F:13    1240
Name: mac, dtype: int64

In [ ]:
df

                      timestamp             sensor                mac  rssi
0    2026-03-01 13:27:41.463329  8C:AA:B5:48:4F:13  54:1f:8d:da:d6:9d   -76
1    2026-03-01 13:27:41.463329  8C:AA:B5:48:4F:13  30:16:9d:88:47:90   -60
2    2026-03-01 13:27:41.463329  8C:AA:B5:48:4F:13  14:33:75:ab:0f:71   -76
3    2026-03-01 13:27:41.463329  8C:AA:B5:48:4F:13  a4:91:b1:bf:11:77   -63
4    2026-03-01 13:27:41.463329  8C:AA:B5:48:4F:13  6c:99:61:24:54:b4   -83
...                         ...                ...                ...   ...
1235 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  e0:63:da:b7:68:21   -85
1236 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  14:33:75:ab:0f:71   -77
1237 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  80:16:05:e4:87:08   -86
1238 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  ae:8b:a9:9a:3b:6a   -88
1239 2026-03-01 13:56:44.401222  8C:AA:B5:48:4F:13  d0:b6:6f:57:6b:75   -86

[1240 rows x 4 columns]

[13:57:18] Logged 12 devices from 8C:AA:B5:48:4F:13[13:57:18] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:57:53] Logged 12 devices from 8C:AA:B5:48:4F:13[13:57:53] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:58:27] Logged 12 devices from 8C:AA:B5:48:4F:13
[13:58:27] Logged 12 devices from 8C:AA:B5:48:4F:13
[13:59:02] Logged 12 devices from 8C:AA:B5:48:4F:13[13:59:02] Logged 12 devices from 8C:AA:B5:48:4F:13

[13:59:37] Logged 12 devices from 8C:AA:B5:48:4F:13[13:59:37] Logged 12 devices from 8C:AA:B5:48:4F:13

[14:00:11] Logged 12 devices from 8C:AA:B5:48:4F:13[14:00:11] Logged 12 devices from 8C:AA:B5:48:4F:13

[14:00:45] Logged 13 devices from 8C:AA:B5:48:4F:13[14:00:45] Logged 13 devices from 8C:AA:B5:48:4F:13

[14:01:20] Logged 13 devices from 8C:AA:B5:48:4F:13[14:01:20] Logged 13 devices from 8C:AA:B5:48:4F:13

[14:01:55] Logged 15 devices from 8C:AA:B5:48:4F:13
[14:01:55] Logged 15 devices from 8C:AA:B5:48:4F:13
[14:02:29] Logged 13 devices from 8C:AA:B5:48:4F:13
[14:02:29] Logged 13 devices from 8C:AA:B5:48:4F:13
[14:03:04] Logged 16 devices from 8C:AA:B5:48:4F:13
[14:03:04] Logged 16 devices from 8C:AA:B5:48:4F:13
[14:03:39] Logged 14 devices from 8C:AA:B5:48:4F:13[14:03:39] Logged 14 devices from 8C:AA:B5:48:4F:13

[14:04:13] Logged 14 devices from 8C:AA:B5:48:4F:13[14:04:13] Logged 14 devices from 8C:AA:B5:48:4F:13

[14:04:48] Logged 13 devices from 8C:AA:B5:48:4F:13[14:04:48] Logged 13 devices from 8C:AA:B5:48:4F:13

[14:05:23] Logged 12 devices from 8C:AA:B5:48:4F:13[14:05:23] Logged 12 devices from 8C:AA:B5:48:4F:13

[14:05:57] Logged 10 devices from 8C:AA:B5:48:4F:13[14:05:57] Logged 10 devices from 8C:AA:B5:48:4F:13

[14:06:32] Logged 9 devices from 8C:AA:B5:48:4F:13[14:06:32] Logged 9 devices from 8C:AA:B5:48:4F:13

[14:07:07] Logged 12 devices from 8C:AA:B5:48:4F:13[14:07:07] Logged 12 devices from 8C:AA:B5:48:4F:13

[14:07:41] Logged 12 devices from 8C:AA:B5:48:4F:13[14:07:41] Logged 12 devices from 8C:AA:B5:48:4F:13

[14:08:16] Logged 12 devices from 8C:AA:B5:48:4F:13[14:08:16] Logged 12 devices from 8C:AA:B5:48:4F:13